# Generated by Django 3.2.18 on 2023-02-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_pictures/default.jpeg', upload_to='profile_pictures/'),
        ),
    ]
